#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Sun Apr  4 17:56:02 2021
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
import gettext
from UpsDisplayFrame import UpsDisplayFrame


if __name__ == "__main__":
    gettext.install("GenTest") # replace with the appropriate catalog name

    GenTest = wx.PySimpleApp()
    upsdisplayFrame = UpsDisplayFrame(None, wx.ID_ANY, "")
    GenTest.SetTopWindow(upsdisplayFrame)
    upsdisplayFrame.Show()
    GenTest.MainLoop()
