#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

import wx
import gettext

from UpsDisplayFrame import UpsDisplayFrame


if __name__ == "__main__":
    gettext.install("upsdisplay") # replace with the appropriate catalog name

    UpsDisplay = wx.App()
    upsdisplayFrame = UpsDisplayFrame(None, wx.ID_ANY, "")
    UpsDisplay.SetTopWindow(upsdisplayFrame)
    upsdisplayFrame.Show()
    UpsDisplay.MainLoop()
